env:
  global:
    - secure: dQm6A7+yuwJTXrnZehIhCSX0NS9amJ8EZE6e2cD4KMKhxqoThsSuKBWmMrb3iT9l3fYhgFakc/W6jdSrsmglmcUUqdmUNCnDSB5q3Nb9cThYT6F7Ueyxl7n8Hz1RiuEl7qef/Ze45Ej481L86dctWWblB/hcywh6d+hTR0+r0O8=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - make deps
script:
  - make
  - make test
  - make docs
  - make examples
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh