[package]
name = "rustful"
version = "0.1.0"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
exclude = ["scripts/*", "examples/*", ".travis.yml", ".gitignore"]
description = "A light web micro-framework with the ambition of being simple, modular and non-intrusive."
documentation = "http://ogeon.github.io/docs/rustful/master/rustful/index.html"
repository = "https://github.com/Ogeon/rustful"
readme = "README.md"
keywords = ["web", "micro", "framework", "http", "https", "routing"]
license = "MIT"

[lib]
name = "rustful"
path = "src/lib.rs"

[features]
nightly = ["hyper/nightly", "anymap/nightly"]

[dependencies]
hyper = "0.3"
time = "0.1"
url = "0.2"
anymap = "0.10"

[dev-dependencies]
tempdir = "0.3"
