[package]

name = "rustful"
version = "0.1.0-pre"
authors = ["hello@erikhedvall.nu"]

[lib]

name = "rustful"
path = "src/lib.rs"

[dependencies.rustful_macros]

path = "macros"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http"

[dependencies.time]
git = "https://github.com/rust-lang/time"